// try {
//     // Code that might throw an error
// } catch (error) {
//     // Code to handle the error
// } finally {
//     // Code that will run regardless of whether an error occurred or not
// }




let a=10
let b=5
console.log(a)
console.log(b)
console.log(a+b)
console.log(a-b)
try{
    console.log(a+c) 
}catch(error){
    console.log(error)
    
}finally{
    console.log("error solved")
}              
console.log(a*b)
console.log(a/b)
